version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "3000:3000"
    nginx:
        restart: always
        build:
            context: ./nginx #location of Dockerfile for this service
        ports:
            - "80:80" #port mapping from local machine -> docker port